### ISSUE TITLE
После обновления на v0.11 ошибка возникла в пользовательской интеграции

### ISSUE THREAD

**Issue by vlad36N** [alryaz/hass-tns-energo#13]
Привет!
Home Assistant 2023.6.2 
Supervisor 2023.06.2 
Operating System 10.3 
Пользовательский интерфейс 20230608.0 - latest 
Личный кабинет ТНС Энерго version v0.11 
Эта ошибка возникла в пользовательской интеграции.

Logger: homeassistant.config_entries
Source: custom_components/tns_energo/__init__.py:275
Integration: ТНС Энерго (documentation, issues)
First occurred: 13:29:10 (3 occurrences)
Last logged: 13:31:23

Error setting up entry XXXXXXXXXXXX for tns_energo
Traceback (most recent call last):
  File "/config/custom_components/tns_energo/__init__.py", line 257, in async_setup_entry
    accounts = await api_object.async_get_accounts_list()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tns_energo_api/__init__.py", line 311, in async_get_accounts_list
    response = await GetLSListByLS.async_request(self, code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tns_energo_api/requests/account.py", line 241, in async_request
    return cls.from_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tns_energo_api/converters.py", line 189, in from_response
    raise ResponseException(code, msg)
tns_energo_api.exceptions.ResponseException: (110, 'Невозможно получить список управляемых счетов')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tns_energo/__init__.py", line 275, in async_setup_entry
    + str(e)
          ^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value

**Comment by RipZ** [comment]
Аналогичная ситуация
