### ISSUE TITLE
Невозможно получить список управляемых счетов

### ISSUE THREAD

**Issue by elagin** [alryaz/hass-tns-energo#17]
Возможно связано с #16 

Регистратор: homeassistant.config_entries
Источник: config_entries.py:640
Первое сообщение: 10:09:52 (1 сообщений)
Последнее сообщение: 10:09:52

Error setting up entry XXXXXXXXX for tns_energo
Traceback (most recent call last):
  File "/config/custom_components/tns_energo/__init__.py", line 257, in async_setup_entry
    accounts = await api_object.async_get_accounts_list()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tns_energo_api/__init__.py", line 311, in async_get_accounts_list
    response = await GetLSListByLS.async_request(self, code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tns_energo_api/requests/account.py", line 241, in async_request
    return cls.from_response(response)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tns_energo_api/converters.py", line 189, in from_response
    raise ResponseException(code, msg)
tns_energo_api.exceptions.ResponseException: (110, 'Невозможно получить список управляемых счетов')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tns_energo/__init__.py", line 275, in async_setup_entry
    + str(e)
          ^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value

**Comment by kirill-k2** [comment]
@elagin есть возможность проверить патч выше? у меня нет логина ТНС для проверки локально.

**Comment by elagin** [comment]
Видимо исправилось. Сейчас счет и баланс отображается.
