### ISSUE TITLE
Ошибка интеграции после обновления HA до 12.0 (12.1)

### ISSUE THREAD

**Issue by drts-sv** [alryaz/hass-tns-energo#7]
ПОсле обновления HA core до 12.0 возникает ошибка интеграции. 
`Logger: homeassistant.config_entries
Source: custom_components/tns_energo/__init__.py:233
Integration: ТНС Энерго (documentation, issues)
First occurred: 10:18:52 (1 occurrences)
Last logged: 10:18:52

Error setting up entry 230104002840 for tns_energo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tns_energo/__init__.py", line 233, in async_setup_entry
    await api_object.async_authenticate()
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/__init__.py", line 295, in async_authenticate
    response = await AuthorizationRequest.async_request(self, self._username, self._password)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/authorization.py", line 100, in async_request
    return cls.from_response(result)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 174, in from_response
    if not conv_bool(data["result"]):
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 21, in conv_bool
    raise ValueError("invalid boolean value")
ValueError: invalid boolean value`

**Comment by drts-sv** [comment]
Видимо чтото на сайте тнс глючило. Все восстановилось.
