### ISSUE TITLE
Атрибуты в HA 2022.4

### ISSUE THREAD

**Issue by alexfrolkin** [alryaz/hass-tns-energo#8]
В последней версии HA, как я понял, больше нет атрибутов. Обновите, пожалуйста, интеграцию, что бы атрибуты были как объекты, т.к. в них содержится очень важная информация. В счётчике, допустим, последние переданные показания.
До обновления HA:
![Screenshot_20220409-125803_Home Assistant](https://user-images.githubusercontent.com/77844696/162567539-f75da1a9-3d02-4f8f-9327-42517402d865.jpg)
После обновления HA:
![Screenshot_20220409-130849_Home Assistant](https://user-images.githubusercontent.com/77844696/162567567-83147d0e-04cb-4674-80cc-94f227079116.jpg)

Заранее благодарен !

**Comment by alryaz** [comment]
@alexfrolkin Прошу поставить версию "master" из HACS и протестировать (самостоятельно не выйдет, логина/пароля нет). Фикс предложен.

В HACS на компоненте потребуется:
- Нажать "Update Information" ("Обновить информацию")
- Нажать "Reinstall" ("Переустановить")
- Выбрать версию "master" из выпадающего списка (может потребоваться отметить галочку "show beta versions" ("показывать бета-версии"))

**Comment by alex2beard** [comment]
Версии master в списке нет после обновления информации, пробовал  main и самую последнюю, проблема с атрибутами осталась. Так же пробовал полную переустановки, не помогло.
![Screenshot_20220413-062610_Home Assistant](https://user-images.githubusercontent.com/77844696/163096302-b3b217b4-8cc3-4ba1-903d-42d448cc3656.jpg)

**Comment by LAlexe** [comment]
Не помогает. Бета версия не доступна. Но и перенос вручную так же не даёт эффекта.
device_class: tns_energo_meter
icon: mdi:counter
friendly_name:  <номер ЛС> Счётчик <номер счётчика>
и всё.

**Comment by alex2beard** [comment]
Уважаемый @alryaz , подскажите, есть ли в планах исправление проблемы с атрибутами ? Мы вас не торопим, конечно, но хочется понять, переделывать ли в своей системе объекты, которые были созданы из значений атрибутов.

**Comment by esnet146** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.tns_energo._base
Source: custom_components/tns_energo/sensor.py:357
Integration: ТНС Энерго (documentation, issues)
First occurred: 19:41:36 (1 occurrences)
Last logged: 19:41:36

Error occurred during task execution: TypeError("__init__() missing 6 required keyword-only arguments: 'transmission_coefficient', 'max_indication_difference', 'can_delete', 'model', 'service_number', and 'service_name'")
Traceback (most recent call last):
  File "/config/custom_components/tns_energo/_base.py", line 182, in _wrap_update_task
    return await update_task
  File "/config/custom_components/tns_energo/sensor.py", line 357, in async_refresh_accounts
    meters = await account.async_get_meters()
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/__init__.py", line 368, in async_get_meters
    response = await SendIndicationsPage.async_request(self.api, self.code)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/get_send_indications_page.py", line 188, in async_request
    return cls.from_response(result)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 191, in from_response
    return super().from_response(data, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 159, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init tns_energo_api.requests.get_send_indications_page.SendIndicationsPage>", line 4, in __init__
    _setattr('counters', __attr_converter_counters(counters))
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/get_send_indications_page.py", line 156, in converter__counters
    {
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/get_send_indications_page.py", line 158, in <dictcomp>
    sorted(
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/get_send_indications_page.py", line 163, in <genexpr>
    else ZoneData.from_response(tariff_data)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 159, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: __init__() missing 6 required keyword-only arguments: 'transmission_coefficient', 'max_indication_difference', 'can_delete', 'model', 'service_number', and 'service_name'

**Comment by vlad36N** [comment]
Здравствуйте. Поставил  Бета версию v0.1.0, атрибутов нет.

**Comment by alex2beard** [comment]
Поднимем тему !

**Comment by anton-spec** [comment]
Поднимаем тему - или проект заброшен? v0.1.1
device_class: tns_energo_meter
icon: mdi:counter
friendly_name: 365ХХХХХХХХХХ Счётчик 5940ХХХ
