### ISSUE TITLE
Ошибка при добавлении интеграции

### ISSUE THREAD

**Issue by evsmorodin** [alryaz/hass-tns-energo#9]
Добрый день!

При попытке добавления интеграции получаю ошибку

```
Эта ошибка возникла в кастомной интеграции.

Logger: aiohttp.server
Source: custom_components/tns_energo/config_flow.py:111
Integration: ТНС Энерго (documentation, issues)
First occurred: 12:57:31 (1 occurrences)
Last logged: 12:57:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tns_energo/config_flow.py", line 111, in async_step_user
    await api.async_authenticate()
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/__init__.py", line 295, in async_authenticate
    response = await AuthorizationRequest.async_request(self, self._username, self._password)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/authorization.py", line 100, in async_request
    return cls.from_response(result)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 191, in from_response
    return super().from_response(data, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 159, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
  File "<attrs generated init tns_energo_api.requests.authorization.AuthorizationRequest>", line 9, in __init__
    _setattr('_email_and_invoice_status', __attr_converter__email_and_invoice_status(email_and_invoice_status))
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/requests/authorization.py", line 79, in _converter__email_and_kvit_status
    return EmailAndKvitStatus.from_response(value)
  File "/usr/local/lib/python3.9/site-packages/tns_energo_api/converters.py", line 159, in from_response
    return cls(**init_args)  # type: ignore[call-arg]
TypeError: __init__() missing 1 required keyword-only argument: 'code'
```

Есть предположение, что это связано с тем, что мой ЛК находится тут: `https://lk.kuban.tns-e.ru/`

**Comment by alryaz** [comment]
Здравствуйте! Напишите, пожалуйста, в Telegram: https://t.me/alryaz.

Это проблема уровня данных; надо понять, что не отдаётся сервером.
